### ISSUE TITLE
Inconsistency in Predicted Output Values for gRNAs in Zero-Shot Prediction 

### ISSUE THREAD

**Issue by aashutoshb97** [qwang897/Uni-deepSG#1]
Hello,
I've been exploring your work for zero-shot prediction using the provided scripts. I've applied the scripts to predict outcomes for gRNAs that we've tested in our lab in a fungal species. However, I've noticed a peculiar issue—each time I run the script, the predicted output values for the same gRNAs seem to change.

To illustrate this inconsistency, I've attached images comparing the predicted values from two separate script runs. I'd greatly appreciate your insights into why this variation is occurring and any suggestions on ensuring more stable and reproducible predictions.

Thank you for your time and assistance.

![Uni-deepSG_vs_experimental_efficiency](https://github.com/qwang897/Uni-deepSG/assets/60017121/c5fde26e-e76d-4964-b90f-492349f1624d)

![Uni-deepSG_vs_experimental_efficiency_v2](https://github.com/qwang897/Uni-deepSG/assets/60017121/d015de65-1bc6-41ac-9378-2e0112d3e1ab)

**Comment by qwang897** [comment]
Hello, thank you very much for your question.
1. We just checked the updated code and found that we forgot to close the dropout (which will reproduce a random number each time). Now we have fixed the bug. You should get exactly the same answer from identical inputs. Thank you very much for finding this bug.
2. We note that the model is designed to get a good "spearman correlation" between predicted editing efficiency and the real efficiency. If you want to get a better estimation to the "absolute value" of the efficiency, you can try to adjust two parameters, a and b. There are two ways to do so.
(1) use our pre-setted values: in "XXX", you can change XX[0] to XX[9]
(2) manually input a and b: in "XXX", 
In either way, the values of a and b will not change the spearman correlation. However, appropriate a and b lead to better predictions for the absolute values of efficiencies.

**Comment by aashutoshb97** [comment]
Hi,
Thank you for the quick response. The updates you made makes sense. However, the scripts are running into an error:
Traceback (most recent call last):
  File "code/Uni-deepSG/PredictionTools/predict.py", line 37, in <module>
    eff = net(input,typ,Train = False)
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'Train'

I assume you might need to change the trained model uploaded to GitHub. Please let me know if I am wrong. Thank you.


Regards,

Aashutosh Boob

PhD Candidate - Zhao Lab<http://faculty.scs.illinois.edu/~zhaogrp/index.html>

Chemical and Biomolecular Engineering

University of Illinois at Urbana-Champaign


109 IGB, Urbana, IL 61801

***@***.******@***.***> | 217-305-2607

________________________________

**Comment by qwang897** [comment]
Hello, thank you very much for your question.
We just checked the updated code and found that we forgot to close the dropout (which will reproduce a random number each time). Now we have fixed the bug. You should get exactly the same answer from identical inputs. Thank you very much for finding this bug.
We note that the model is designed to get a good "spearman correlation" between predicted editing efficiency and the real efficiency. If you want to get a better estimation to the "absolute value" of the efficiency, you can try to adjust two parameters, a and b. There are two ways to do so.
(1) use our pre-defined values: in predict.ipynb, "typ = torch.LongTensor([[2]]).cuda()", you can change the number in the brackets from 2 to any integer (from 0 to 10).
(2) manually input a and b: in "train.py", define the values in "bt[:,:,0]=a,bt[:,:,1]=b", then delete the “#”. In the normal case, a and b should locate within [-5,5]. 
In either way, the values of a and b will not change the spearman correlation. However, appropriate a and b lead to better predictions for the absolute values of efficiencies.
now the code should be run correctly.

**Comment by aashutoshb97** [comment]
Thank you, it works now!
